import React, { useState } from 'react';
import { CheckCircle2, AlertTriangle, XCircle, ArrowDown, ExternalLink, ShieldCheck, Database, Layers } from 'lucide-react';
import { ClaimValidationItem } from '../types/intelligence';

interface AIClaimValidationPanelProps {
  claims: ClaimValidationItem[];
  onHighlightSource?: (sourceId: string) => void;
}

export const AIClaimValidationPanel: React.FC<AIClaimValidationPanelProps> = ({
  claims,
  onHighlightSource,
}) => {
  const [selectedClaimId, setSelectedClaimId] = useState<string>(claims[0]?.id || 'CLM-01');

  const selectedClaim = claims.find((c) => c.id === selectedClaimId) || claims[0];

  return (
    <div id="sec-claim-validation" className="rounded-xl border border-sky-300 bg-white p-5 shadow-sm shadow-sky-100/60">
      {/* Header */}
      <div className="flex flex-wrap items-center justify-between gap-3 border-b border-sky-100 pb-3.5">
        <div>
          <div className="flex items-center gap-2 font-mono text-xs font-semibold text-emerald-700">
            <CheckCircle2 className="h-4 w-4" />
            <span>STAGE 06 · EVIDENCE CHAIN & CLAIM VALIDATION ENGINE</span>
          </div>
          <h3 className="font-display text-lg font-bold text-slate-900 tracking-wide mt-0.5">
            AI CLAIM VALIDATION
          </h3>
          <p className="text-xs text-slate-600 mt-0.5">
            Every statement generated by the copilot is decomposed into discrete propositions and checked against verified spacecraft telemetry.
          </p>
        </div>

        <div className="flex items-center gap-1.5 font-mono text-xs text-slate-600">
          <span className="rounded-md bg-emerald-100 px-2.5 py-0.5 text-emerald-800 font-bold border border-emerald-300">
            ZERO HALLUCINATION TOLERANCE
          </span>
        </div>
      </div>

      <div className="mt-4 grid grid-cols-1 lg:grid-cols-12 gap-4">
        {/* Left Column: All Extracted Claims & Verification Verdicts */}
        <div className="lg:col-span-7 space-y-2.5">
          <div className="font-mono text-xs font-bold text-slate-700 mb-2">
            PROPOSITIONS EXTRACTED FROM COPILOT SYNTHESIS:
          </div>

          {claims.map((item) => {
            const isSelected = item.id === selectedClaimId;
            const isSupported = item.status === 'SUPPORTED';
            const isPartial = item.status === 'PARTIALLY_SUPPORTED';
            const isNotEstablished = item.status === 'NOT_ESTABLISHED';

            return (
              <div
                key={item.id}
                onClick={() => {
                  setSelectedClaimId(item.id);
                  if (onHighlightSource) onHighlightSource(item.sourceId);
                }}
                className={`rounded-xl border p-3.5 transition-all cursor-pointer ${
                  isSelected
                    ? 'border-sky-500 bg-sky-50/70 shadow-sm ring-2 ring-sky-400/40'
                    : 'border-slate-200 bg-white hover:border-sky-300 hover:bg-slate-50/60'
                }`}
              >
                <div className="flex items-start justify-between gap-2">
                  <div className="flex items-center gap-2 font-mono text-xs">
                    <span className="font-bold text-slate-600">{item.id}</span>
                    <span className="text-slate-300">·</span>
                    <span className="text-slate-700 font-semibold">{item.parameter}</span>
                  </div>

                  {/* Verification Badge */}
                  <span
                    className={`rounded-md px-2 py-0.5 font-mono text-[10px] font-bold flex items-center gap-1 shrink-0 ${
                      isSupported
                        ? 'bg-emerald-100 text-emerald-800 border border-emerald-300'
                        : isPartial
                        ? 'bg-amber-100 text-amber-800 border border-amber-300'
                        : 'bg-rose-100 text-rose-800 border border-rose-300'
                    }`}
                  >
                    {isSupported ? (
                      <CheckCircle2 className="h-3 w-3" />
                    ) : isPartial ? (
                      <AlertTriangle className="h-3 w-3" />
                    ) : (
                      <XCircle className="h-3 w-3" />
                    )}
                    {item.status.replace('_', ' ')}
                  </span>
                </div>

                <div className="mt-2 text-xs font-semibold text-slate-900 leading-snug">
                  "{item.claim}"
                </div>

                <div className="mt-2 flex items-center justify-between font-mono text-[11px] text-slate-500 border-t border-slate-100 pt-1.5">
                  <span className="text-sky-800 font-bold">Source: [{item.sourceId}]</span>
                  <span>{item.timestamp}</span>
                </div>
              </div>
            );
          })}
        </div>

        {/* Right Column: Deep Evidence Chain for Selected Claim */}
        <div className="lg:col-span-5 rounded-xl border border-sky-300 bg-sky-50/40 p-4 shadow-xs">
          <div className="flex items-center justify-between border-b border-sky-200 pb-2.5">
            <span className="font-mono text-xs font-bold text-sky-900">
              TRACEABLE EVIDENCE CHAIN
            </span>
            <span className="font-mono text-[11px] text-sky-700 font-semibold">
              CLAIM: {selectedClaim.id}
            </span>
          </div>

          {/* Stepped Evidence Chain Visual */}
          <div className="mt-3.5 space-y-2.5 font-mono text-xs">
            {/* Step 1: AI Claim */}
            <div className="rounded-lg border border-slate-200 bg-white p-2.5 shadow-xs">
              <div className="text-[10px] text-slate-400 font-semibold">AI CLAIM</div>
              <div className="mt-1 font-bold text-slate-900 font-sans text-xs">
                "{selectedClaim.claim}"
              </div>
            </div>

            <div className="flex justify-center text-sky-400">
              <ArrowDown className="h-3.5 w-3.5" />
            </div>

            {/* Step 2: Source */}
            <div className="rounded-lg border border-slate-200 bg-white p-2.5 shadow-xs">
              <div className="text-[10px] text-slate-400 font-semibold">VERIFIED SOURCE</div>
              <div className="mt-1 font-bold text-sky-800 text-xs flex items-center justify-between">
                <span>[{selectedClaim.sourceId}]</span>
                <span className="text-[10px] text-slate-500 font-normal">{selectedClaim.timestamp}</span>
              </div>
            </div>

            <div className="flex justify-center text-sky-400">
              <ArrowDown className="h-3.5 w-3.5" />
            </div>

            {/* Step 3: Parameter & Value */}
            <div className="rounded-lg border border-slate-200 bg-white p-2.5 shadow-xs">
              <div className="text-[10px] text-slate-400 font-semibold">DOWNLINKED SENSOR TELEMETRY</div>
              <div className="mt-1 flex items-center justify-between text-xs">
                <span className="text-slate-700 font-medium">{selectedClaim.parameter}</span>
                <span className="font-bold text-slate-900">{selectedClaim.telemetryValue}</span>
              </div>
            </div>

            <div className="flex justify-center text-sky-400">
              <ArrowDown className="h-3.5 w-3.5" />
            </div>

            {/* Step 4: Verification Verdict */}
            <div
              className={`rounded-lg border p-3 shadow-xs ${
                selectedClaim.status === 'SUPPORTED'
                  ? 'border-emerald-300 bg-emerald-50'
                  : selectedClaim.status === 'PARTIALLY_SUPPORTED'
                  ? 'border-amber-300 bg-amber-50'
                  : 'border-rose-300 bg-rose-50'
              }`}
            >
              <div className="text-[10px] font-bold text-slate-600">VALIDATION AUDIT VERDICT</div>
              <div className="mt-1 font-bold text-sm text-slate-900">
                {selectedClaim.status === 'SUPPORTED' && '✓ SUPPORTED BY REAL TELEMETRY'}
                {selectedClaim.status === 'PARTIALLY_SUPPORTED' && '⚡ PARTIALLY SUPPORTED (INCOMPLETE)'}
                {selectedClaim.status === 'NOT_ESTABLISHED' && '⚠ NOT ESTABLISHED (REJECTED CAUSATION)'}
              </div>
              <p className="mt-1.5 text-xs text-slate-700 font-sans leading-relaxed">
                {selectedClaim.reason}
              </p>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};
